Repository three-iii/AI_B2B_Project, pull requests merged in 2024-09, with the labels that each got.

#3 .gitignore docker-compose.yml 파일 생성
  .gitignore
  docker-compose.yml
Labels: build

#4 feat: User 도메인 생성 및 기본 세팅
  com.three-iii.service/src/main/java/com/three_iii/service/application/UserService.java
  com.three-iii.service/src/main/java/com/three_iii/service/controller/UserController.java
  com.three-iii.service/src/main/java/com/three_iii/service/domain/Role.java
  com.three-iii.service/src/main/java/com/three_iii/service/domain/User.java
  com.three-iii.service/src/main/java/com/three_iii/service/domain/repository/UserRepository.java
Labels: feat

#9 feat(#6): Company 도메인 생성
  com.three-iii.service/src/main/java/com/three_iii/service/domain/Company.java
  com.three-iii.service/src/main/java/com/three_iii/service/domain/CompanyStatusEnum.java
Labels: feat

#16 feat: ApplicationException HttpStatus 추가
  com.three-iii.service/src/main/java/com/three_iii/service/exception/ApplicationException.java
  com.three-iii.service/src/main/java/com/three_iii/service/exception/ExceptionManager.java
Labels: feat

#14 Feat/#10 company create
  com.three-iii.service/src/main/java/com/three_iii/service/application/CompanyService.java
  com.three-iii.service/src/main/java/com/three_iii/service/application/dto/CompanyCreateRequest.java
  com.three-iii.service/src/main/java/com/three_iii/service/application/dto/CompanyCreateResponse.java
  com.three-iii.service/src/main/java/com/three_iii/service/controller/CompanyController.java
  com.three-iii.service/src/main/java/com/three_iii/service/domain/Company.java
  com.three-iii.service/src/main/java/com/three_iii/service/domain/CompanyTypeEnum.java
  com.three-iii.service/src/main/java/com/three_iii/service/domain/repository/CompanyRepository.java
  com.three-iii.service/src/main/java/com/three_iii/service/exception/ErrorCode.java
Labels: feat

#19 feat: 회원가입 API
  com.three-iii.service/build.gradle
  com.three-iii.service/docs/auth-api.http
  com.three-iii.service/src/main/java/com/three_iii/service/application/AuthService.java
  com.three-iii.service/src/main/java/com/three_iii/service/application/UserService.java
  com.three-iii.service/src/main/java/com/three_iii/service/application/dto/SignUpRequestDto.java
  com.three-iii.service/src/main/java/com/three_iii/service/config/PasswordEncoderConfig.java
  com.three-iii.service/src/main/java/com/three_iii/service/config/SecurityConfig.java
  com.three-iii.service/src/main/java/com/three_iii/service/controller/AuthController.java
  com.three-iii.service/src/main/java/com/three_iii/service/controller/UserController.java
  com.three-iii.service/src/main/java/com/three_iii/service/domain/Role.java
  com.three-iii.service/src/main/java/com/three_iii/service/domain/User.java
  com.three-iii.service/src/main/java/com/three_iii/service/domain/repository/UserRepository.java
  com.three-iii.service/src/main/java/com/three_iii/service/exception/ErrorCode.java
Labels: feat

#21 Feat/#18 company find
  com.three-iii.service/src/main/java/com/three_iii/service/PageableAspect.java
  com.three-iii.service/src/main/java/com/three_iii/service/application/CompanyService.java
  com.three-iii.service/src/main/java/com/three_iii/service/application/dto/CompanyFindResponse.java
  com.three-iii.service/src/main/java/com/three_iii/service/config/JPAConfig.java
  com.three-iii.service/src/main/java/com/three_iii/service/config/SecurityConfig.java
  com.three-iii.service/src/main/java/com/three_iii/service/controller/CompanyController.java
  com.three-iii.service/src/main/java/com/three_iii/service/domain/repository/CompanyRepository.java
  com.three-iii.service/src/main/java/com/three_iii/service/domain/repository/CompanyRepositoryCustom.java
  com.three-iii.service/src/main/java/com/three_iii/service/domain/repository/CompanyRepositoryImpl.java
  com.three-iii.service/src/main/java/com/three_iii/service/exception/ErrorCode.java
Labels: feat

#23 Feat/#22 company update
  com.three-iii.service/src/main/java/com/three_iii/service/application/CompanyService.java
  com.three-iii.service/src/main/java/com/three_iii/service/application/dto/CompanyUpdateRequest.java
  com.three-iii.service/src/main/java/com/three_iii/service/application/dto/CompanyUpdateResponse.java
  com.three-iii.service/src/main/java/com/three_iii/service/controller/CompanyController.java
  com.three-iii.service/src/main/java/com/three_iii/service/domain/BaseEntity.java
  com.three-iii.service/src/main/java/com/three_iii/service/domain/Company.java
  com.three-iii.service/src/main/java/com/three_iii/service/domain/repository/CompanyRepository.java
Labels: feat

#48 enhance(#45): gateway swagger 적용 (auth, company)
  com.three-iii.company/src/main/java/com/three_iii/company/config/SecurityConfig.java
  com.three-iii.company/src/main/java/com/three_iii/company/config/SwaggerConfig.java
  com.three-iii.company/src/main/java/com/three_iii/company/filter/AuthenticationFilter.java
  com.three-iii.company/src/main/resources/application.yml
  com.three-iii.gateway/build.gradle
  com.three-iii.gateway/src/main/java/com/three_iii/gateway/filter/AuthenticationFilter.java
  com.three-iii.gateway/src/main/resources/application.yml
  com.three-iii.user/src/main/java/com/three_iii/user/config/SwaggerConfig.java
  com.three-iii.user/src/main/java/com/three_iii/user/filter/AuthenticationFilter.java
  com.three-iii.user/src/main/resources/application.yml
Labels: enhance

#46 feat: 배송담당자 도메인 생성
  com.three-iii.user/docs/client/auth-api.http
  com.three-iii.user/src/main/java/com/three_iii/user/application/ShipperService.java
  com.three-iii.user/src/main/java/com/three_iii/user/domain/Shipper.java
  com.three-iii.user/src/main/java/com/three_iii/user/domain/ShipperType.java
  com.three-iii.user/src/main/java/com/three_iii/user/domain/repository/ShipperRepository.java
  com.three-iii.user/src/main/java/com/three_iii/user/presentation/AuthController.java
  com.three-iii.user/src/main/java/com/three_iii/user/presentation/ShipperController.java
  com.three-iii.user/src/main/java/com/three_iii/user/presentation/UserController.java
Labels: feat

#51 feat: 배송담당자 생성 API 및 Role 체크를 위한 어노테이션 추가
  com.three-iii.gateway/src/main/resources/application.yml
  com.three-iii.user/docs/client/auth-api.http
  com.three-iii.user/docs/client/shippers-api.http
  com.three-iii.user/src/main/java/com/three_iii/user/application/AuthService.java
  com.three-iii.user/src/main/java/com/three_iii/user/application/ShipperService.java
  com.three-iii.user/src/main/java/com/three_iii/user/application/dto/ShipperDto.java
  com.three-iii.user/src/main/java/com/three_iii/user/config/SecurityConfig.java
  com.three-iii.user/src/main/java/com/three_iii/user/domain/Shipper.java
  com.three-iii.user/src/main/java/com/three_iii/user/domain/User.java
  com.three-iii.user/src/main/java/com/three_iii/user/domain/repository/ShipperRepository.java
  com.three-iii.user/src/main/java/com/three_iii/user/exception/ErrorCode.java
  com.three-iii.user/src/main/java/com/three_iii/user/exception/ExceptionManager.java
  com.three-iii.user/src/main/java/com/three_iii/user/exception/UserException.java
  com.three-iii.user/src/main/java/com/three_iii/user/filter/AuthenticationFilter.java
  com.three-iii.user/src/main/java/com/three_iii/user/presentation/ShipperController.java
  com.three-iii.user/src/main/java/com/three_iii/user/presentation/dtos/ShipperCreateRequest.java
Labels: feat

#53 feat: company Service Role check & Soft delete
  com.three-iii.company/src/main/java/com/three_iii/company/application/dtos/company/CompanyResponse.java
  com.three-iii.company/src/main/java/com/three_iii/company/application/service/CompanyService.java
  com.three-iii.company/src/main/java/com/three_iii/company/application/service/ProductService.java
  com.three-iii.company/src/main/java/com/three_iii/company/config/SecurityConfig.java
  com.three-iii.company/src/main/java/com/three_iii/company/domain/BaseEntity.java
  com.three-iii.company/src/main/java/com/three_iii/company/domain/Company.java
  com.three-iii.company/src/main/java/com/three_iii/company/presentation/CompanyController.java
  com.three-iii.company/src/main/java/com/three_iii/company/presentation/ProductController.java
Labels: feat

#59 feat: 배송담당자 전체 조회, 수정, 삭제 API
  com.three-iii.user/build.gradle
  com.three-iii.user/docs/client/shippers-api.http
  com.three-iii.user/src/main/java/com/three_iii/user/UserApplication.java
  com.three-iii.user/src/main/java/com/three_iii/user/application/ShipperService.java
  com.three-iii.user/src/main/java/com/three_iii/user/domain/BaseEntity.java
  com.three-iii.user/src/main/java/com/three_iii/user/domain/Shipper.java
  com.three-iii.user/src/main/java/com/three_iii/user/domain/repository/ShipperRepository.java
  com.three-iii.user/src/main/java/com/three_iii/user/exception/ErrorCode.java
  com.three-iii.user/src/main/java/com/three_iii/user/infrastructure/HubClient.java
  com.three-iii.user/src/main/java/com/three_iii/user/presentation/ShipperController.java
  com.three-iii.user/src/main/java/com/three_iii/user/presentation/dtos/ShipperReadResponse.java
  com.three-iii.user/src/main/java/com/three_iii/user/presentation/dtos/ShipperUpdateRequest.java
Labels: feat

#71 feat: Shipper 단건 조회 API 구현
  com.three-iii.user/docs/client/shippers-api.http
  com.three-iii.user/src/main/java/com/three_iii/user/application/ShipperService.java
  com.three-iii.user/src/main/java/com/three_iii/user/domain/repository/ShipperRepository.java
  com.three-iii.user/src/main/java/com/three_iii/user/presentation/ShipperController.java
Labels: feat

#72 feat: AuditorAware 구현
  com.three-iii.user/docs/client/auth-api.http
  com.three-iii.user/docs/client/shippers-api.http
  com.three-iii.user/src/main/java/com/three_iii/user/config/JPAConfig.java
  com.three-iii.user/src/main/java/com/three_iii/user/domain/AuditorAwareImpl.java
  com.three-iii.user/src/main/java/com/three_iii/user/domain/BaseEntity.java
  com.three-iii.user/src/main/java/com/three_iii/user/domain/User.java
Labels: feat

#80 feat: 배송담당자 타입별 조회 API 구현
  com.three-iii.user/docs/client/auth-api.http
  com.three-iii.user/docs/client/shippers-api.http
  com.three-iii.user/src/main/java/com/three_iii/user/application/ShipperService.java
  com.three-iii.user/src/main/java/com/three_iii/user/config/FeignConfig.java
  com.three-iii.user/src/main/java/com/three_iii/user/domain/repository/ShipperRepository.java
  com.three-iii.user/src/main/java/com/three_iii/user/infrastructure/HubClient.java
  com.three-iii.user/src/main/java/com/three_iii/user/presentation/ShipperController.java
  com.three-iii.user/src/main/resources/application.yml
Labels: feat

#84 feat: 배송담당자에게 알림 생성 스케줄러 구현
  com.three-iii.order/src/main/java/com/three_iii/order/application/DeliveryService.java
  com.three-iii.order/src/main/java/com/three_iii/order/application/OrderService.java
  com.three-iii.order/src/main/java/com/three_iii/order/application/dto/DeliveryResponseDto.java
  com.three-iii.order/src/main/java/com/three_iii/order/controller/DeliveryController.java
  com.three-iii.order/src/main/java/com/three_iii/order/controller/OrderController.java
  com.three-iii.order/src/main/java/com/three_iii/order/domain/Delivery.java
  com.three-iii.order/src/main/java/com/three_iii/order/domain/repository/DeliveryRepository.java
  com.three-iii.order/src/main/java/com/three_iii/order/domain/repository/OrderRepository.java
  com.three-iii.slack/build.gradle
  com.three-iii.slack/src/main/java/com/three_iii/slack/ScheduleService.java
  com.three-iii.slack/src/main/java/com/three_iii/slack/SlackApplication.java
  com.three-iii.slack/src/main/java/com/three_iii/slack/application/service/WeatherInterface.java
  com.three-iii.slack/src/main/java/com/three_iii/slack/application/service/WeatherService.java
  com.three-iii.slack/src/main/java/com/three_iii/slack/config/FeignConfig.java
  com.three-iii.slack/src/main/java/com/three_iii/slack/infrastructure/CompanyClient.java
  com.three-iii.slack/src/main/java/com/three_iii/slack/infrastructure/CompanyResponse.java
  com.three-iii.slack/src/main/java/com/three_iii/slack/infrastructure/CompanyService.java
  com.three-iii.slack/src/main/java/com/three_iii/slack/infrastructure/DeliveryClient.java
  com.three-iii.slack/src/main/java/com/three_iii/slack/infrastructure/DeliveryResponse.java
  com.three-iii.slack/src/main/java/com/three_iii/slack/infrastructure/DeliveryService.java
  com.three-iii.slack/src/main/java/com/three_iii/slack/infrastructure/HubClient.java
  com.three-iii.slack/src/main/java/com/three_iii/slack/infrastructure/HubResponse.java
  com.three-iii.slack/src/main/java/com/three_iii/slack/infrastructure/HubService.java
  com.three-iii.slack/src/main/java/com/three_iii/slack/infrastructure/OrderClient.java
  com.three-iii.slack/src/main/java/com/three_iii/slack/infrastructure/OrderResponse.java
  com.three-iii.slack/src/main/java/com/three_iii/slack/infrastructure/OrderService.java
  com.three-iii.slack/src/main/java/com/three_iii/slack/infrastructure/ShipperResponse.java
  com.three-iii.slack/src/main/java/com/three_iii/slack/infrastructure/UserClient.java
  com.three-iii.slack/src/main/java/com/three_iii/slack/infrastructure/UserService.java
  com.three-iii.slack/src/main/java/com/three_iii/slack/util/JwtUtil.java
  com.three-iii.slack/src/main/resources/application.yml
Labels: feat

#83 feat: 배송담당자 전체조회 시 허브 이름들도 조회할 수 있도록 FeignClient 연동
  com.three-iii.hub/src/main/java/com/three_iii/hub/application/service/HubService.java
  com.three-iii.hub/src/main/java/com/three_iii/hub/domain/repository/HubRepository.java
  com.three-iii.hub/src/main/java/com/three_iii/hub/presentation/HubController.java
  com.three-iii.hub/src/main/java/com/three_iii/hub/presentation/dtos/HubNameFindRequest.java
  com.three-iii.hub/src/main/java/com/three_iii/hub/presentation/dtos/HubNameFindResponse.java
  com.three-iii.user/docs/client/test-api.http
  com.three-iii.user/src/main/java/com/three_iii/user/application/ShipperService.java
  com.three-iii.user/src/main/java/com/three_iii/user/application/dto/HubNameFindRequest.java
  com.three-iii.user/src/main/java/com/three_iii/user/infrastructure/HubClient.java
Labels: feat
